- type: job
  parent: CMJobBase
  id: CMCommandingOfficer
  name: cm-job-name-commanding-officer
  description: cm-job-description-commanding-officer
  playTimeTracker: CMJobCommandingOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
# alteração do pirata
# era:
#     time: 54000 # 15 hours
    time: 36000 # 10 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
# alteração do pirata
# era:
#     time: 36000 # 10 hours
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: CMMilitaryPolice
# alteração do pirata
# era:
#     time: 36000 # 10 hours
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
# alteração do pirata
# era:
#     time: 36000 # 10 hours
    group: CMJobsMedical
# alteração do pirata
# era:
#     time: 36000 # 10 hours
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: CMCommand
# alteração do pirata
# era:
#     time: 36000 # 10 hours
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: CMJobExecutiveOfficer
# alteração do pirata
# era:
#     time: 36000 # 10 hours
    time: 18000 # 5 hrs
  weight: 10
  startingGear: CMGearCommandingOfficer
  icon: "CMJobIconCommandingOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-marine-high-command
  whitelisted: true
  accessGroups:
  - ShipMasterAccess
  minimapIcon:
    sprite: _RMC14/Interface/map_blips.rsi
    state: cic
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillExecution: 1
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSmartGun: 1
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: MarineOrders
    - type: CMVendorUser
      points: 120

- type: startingGear
  id: CMGearCommandingOfficer
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchel
    shoes: CMShoesLaceupCommander
    head: CMHeadBeretCO
    outerClothing: CMCoatOfficer
    id: CMIDCardCommandingOfficer
    ears: CMHeadsetSeniorCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCommandingOfficer
  name: commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMCommandingOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: commanding_officer

- type: playTimeTracker
  id: CMJobCommandingOfficer
